---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calculator-bmi-cm
data:
  NODE_ENV: production
  NODE_LOG_DIR_PATH: './logs/'
  NODE_LOG_LEVEL: 'info'
  NODE_LOG_RETENTION_DAYS: '14d'
  NODE_LOG_RETENTION_MAX_FILE_SIZE: '20m'
  NODE_LOG_SERVICE_NAME: 'calculator-bmi-service'
  NODE_PORT: "80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calculator-bmi
  name: calculator-bmi
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      labels:
        app: calculator-bmi
    spec:
      containers:
      - image: riskirinando/calculator-bmi:latest
        imagePullPolicy: Always
        name: calculator-bmi
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: calculator-bmi-cm
        resources:
          limits:
            cpu: 600m
            memory: 768Mi
          requests:
            cpu: 200m
            memory: 384Mi
  selector:
    matchLabels:
      app: calculator-bmi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: calculator-bmi
  name: calculator-bmi
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: calculator-bmi
  type: ClusterIP
